(() => {
  'use strict';
  const STORAGE_KEY = 'pantry-raccoon:v1';
  const SEED_VERSION = 1;
  const CATEGORIES = ['Produce','Meat & Seafood','Dairy & Refrigerated','Bakery & Bread','Frozen','Pantry','Other'];
  const SPECIALS = [
    {id:'special:out',name:'Go out to Eat',note:'No ingredients. No prep. Everybody wins.'},
    {id:'special:leftovers',name:'Leftovers',note:'Use what is already cooked.'},
    {id:'special:freezer',name:'Freezer / Heat & Eat',note:'A deliberately easy dinner.'},
    {id:'special:undecided',name:'Undecided',note:'Future you can solve this one.'}
  ];

  const SEED_RECIPES = [
    {
      id:'beef-ragu',name:'Slow Cooked Shredded Beef Ragu Pasta',createdBy:'Nagi | RecipeTin Eats',category:'Dinner',servings:'5–6 with pasta',prepMinutes:20,cookMinutes:150,totalMinutes:170,
      url:'https://www.recipetineats.com/slow-cooked-shredded-beef-ragu-pasta/',
      ingredients:['2.5 lb chuck beef, divided into 4 large pieces','1 tbsp salt','Black pepper, to taste','3 tbsp olive oil, divided','3 garlic cloves, minced','1 onion, diced','1 cup diced carrots','1 cup diced celery','28 oz crushed tomatoes','3 tbsp tomato paste','2 beef bouillon cubes, crumbled','1 cup full-bodied red wine or beef broth/stock','1 1/2 cups water for stovetop method','3/4 tsp dried thyme or 3 fresh thyme sprigs','3 dried bay leaves','1 lb dried pappardelle or another wide pasta','Freshly grated Parmesan, for serving','Fresh parsley, finely chopped, optional'],
      instructions:['Pat the beef dry and season with salt and pepper.','Brown the beef aggressively in olive oil, then transfer to a plate.','Cook garlic and onion, then carrots and celery, until softened.','Add tomatoes, tomato paste, bouillon, wine or broth, water, thyme, and bay leaves. Return beef to the pot.','Cover and simmer gently about 2 hours, until the beef pulls apart easily.','Shred the beef and return it to the sauce. Simmer uncovered about 30 minutes until rich and thick.','Cook pappardelle just shy of done, reserving pasta water.','Toss pasta with hot ragu and enough pasta water for the sauce to cling. Serve with Parmesan and parsley.'],
      notes:'Slow cooker option: sear beef and cook the soffritto first. Transfer to slow cooker with remaining ragu ingredients, leaving out the water. Cook LOW 6–8 hours, shred, then reduce sauce if needed.'
    },
    {id:'porter-sunshine-salad',name:'Chicken Apple Sunshine Salad',createdBy:'Porter',category:'Dinner',servings:'3',prepMinutes:15,cookMinutes:15,totalMinutes:30,ingredients:['1 large container mixed greens','1 1/2 pounds chicken breasts, grilled and sliced','1 green apple, chopped or thinly sliced','1 cucumber, chopped','2 tomatoes, chopped','1 cup shredded carrots','1/2 cup blue cheese crumbles','1/3 cup sunflower seeds',"Dressing of each person's choice"],instructions:['Grill or warm the chicken and slice it.','Divide mixed greens among bowls.','Add green apple, cucumber, tomato, and carrots.','Top with chicken, blue cheese, and sunflower seeds.','Serve with dressing choices.'],notes:'Same salad as last week, specifically green apple this time.'},
    {id:'blake-tacos',name:"Blake's Taco Night",createdBy:'Blake',category:'Dinner',servings:'3',prepMinutes:15,cookMinutes:20,totalMinutes:35,ingredients:["Taco protein for Blake's usual taco night",'Taco seasoning','Taco shells or tortillas','Shredded lettuce','Tomatoes','Taco toppings of choice'],instructions:['Prepare the taco filling using Blake’s usual method.','Warm shells or tortillas.','Set out toppings and build tacos.']},
    {id:'freezer-butter-chicken',name:'Freezer Butter Chicken with Rice',createdBy:'Parker',category:'Dinner',servings:'3',prepMinutes:5,cookMinutes:25,totalMinutes:30,ingredients:['1 freezer butter chicken meal','Rice, enough for 3 servings'],instructions:['Heat the freezer butter chicken according to package or freezer-label directions.','Cook rice while it heats.','Serve butter chicken over rice.']},
    {id:'crispy-chicken-cutlets',name:'Crispy Chicken Cutlets with Buttered Noodles & Broccoli',createdBy:'The Mediterranean Dish + Talbot sides',category:'Dinner',servings:'4 cutlets',prepMinutes:20,cookMinutes:10,totalMinutes:30,url:'https://www.themediterraneandish.com/breaded-chicken-cutlets/',ingredients:['4 chicken cutlets or 2 boneless skinless chicken breasts','Kosher salt','Black pepper','1/2 cup all-purpose flour','2 large eggs','1 cup unseasoned breadcrumbs or Panko','1/2 cup grated Parmesan','2 teaspoons Italian seasoning','Extra virgin olive oil, for frying','Lemon wedges, for serving','Buttered noodles, for serving','Broccoli, for serving'],instructions:['Season chicken with salt and pepper.','Set up flour, beaten eggs, and breadcrumbs mixed with Parmesan and Italian seasoning.','Coat chicken in flour, egg, then breadcrumbs. Rest about 10 minutes.','Pan-fry until crisp and golden, about 3 minutes per side.','Serve with lemon wedges, buttered noodles, and broccoli.']}
  ];

  let state = load();
  let toastTimer = null;

  function freshState(){return {version:1,recipes:[],pantry:[],plan:{},groceryReview:{},groceryExtras:[],seedVersion:0,planSeedVersion:0};}
  function load(){try{return {...freshState(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')};}catch{return freshState();}}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}
  function id(){return crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;}
  function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));}
  function lines(value){return String(value||'').split(/\r?\n/).map(v=>v.replace(/^\s*(?:[-*•]|\d+[.)])\s*/,'').trim()).filter(Boolean);}
  function dateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
  function fridayStart(now=new Date()){const d=new Date(now);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()-5+7)%7));return d;}
  function weekDates(){const start=fridayStart();return Array.from({length:8},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d;});}
  function weekKey(){return dateKey(weekDates()[0]);}
  function formatDate(date,opts){return new Intl.DateTimeFormat('en-US',opts).format(date);}
  function currentReview(){state.groceryReview[weekKey()] ||= {};return state.groceryReview[weekKey()];}
  function toast(title,detail=''){const t=document.getElementById('toast');if(!t)return;t.querySelector('strong').textContent=title;t.querySelector('span').textContent=detail;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3200);}

  function ensureSeeds(){
    state.recipes=Array.isArray(state.recipes)?state.recipes:[];
    if(state.seedVersion<SEED_VERSION){SEED_RECIPES.forEach(seed=>{if(!state.recipes.some(r=>r.id===seed.id||r.url&&seed.url&&r.url===seed.url)){state.recipes.push({...seed,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});}});state.seedVersion=SEED_VERSION;}
    if(state.planSeedVersion<1){
      const set=(date,choice,cook)=>{state.plan[`${date}:dinner`] ||= {choice,cook};};
      set('2026-08-08','special:out','Nobody');
      set('2026-08-09','recipe:beef-ragu','Parker');
      set('2026-08-10','recipe:porter-sunshine-salad','Porter');
      set('2026-08-11','recipe:blake-tacos','Blake');
      set('2026-08-12','recipe:freezer-butter-chicken','Parker');
      set('2026-08-13','recipe:crispy-chicken-cutlets','Parker');
      state.planSeedVersion=1;
    }
    save();
  }

  function route(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===name));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===name));const meta={plan:['This week','Friday through Friday. One plan, one grocery list.'],recipes:['Recipe box','Save it once. Cook it whenever.'],pantry:['Pantry','Know what is already in the house.'],grocery:['Grocery review','The meal plan, minus what you already have.']}[name]||['This week','Friday through Friday.'];document.getElementById('pageTitle').textContent=meta[0];document.getElementById('pageSubtitle').textContent=meta[1];location.hash=name;}

  function recipeForChoice(choice){if(!choice?.startsWith('recipe:'))return null;return state.recipes.find(r=>r.id===choice.slice(7))||null;}
  function specialForChoice(choice){return SPECIALS.find(s=>s.id===choice)||null;}
  function choiceOptions(selected=''){const specials=SPECIALS.map(s=>`<option value="${s.id}" ${selected===s.id?'selected':''}>${esc(s.name)}</option>`).join('');const recipes=[...state.recipes].sort((a,b)=>a.name.localeCompare(b.name)).map(r=>`<option value="recipe:${esc(r.id)}" ${selected===`recipe:${r.id}`?'selected':''}>${esc(r.name)}</option>`).join('');return `<option value="">Choose dinner…</option><optgroup label="Real life">${specials}</optgroup><optgroup label="Recipes">${recipes}</optgroup>`;}
  function cookOptions(selected=''){return ['Unassigned','Parker','Blake','Porter','Nobody'].map(v=>`<option ${selected===v?'selected':''}>${v}</option>`).join('');}

  function renderPlan(){const dates=weekDates();document.getElementById('weekRange').textContent=`${formatDate(dates[0],{month:'short',day:'numeric'})} → ${formatDate(dates[7],{month:'short',day:'numeric'})}`;const today=dateKey(new Date());document.getElementById('mealPlan').innerHTML=dates.map(date=>{const key=dateKey(date);const slot=state.plan[`${key}:dinner`]||{choice:'',cook:'Unassigned'};const recipe=recipeForChoice(slot.choice);const special=specialForChoice(slot.choice);const note=recipe?`${recipe.totalMinutes||((recipe.prepMinutes||0)+(recipe.cookMinutes||0))||'?'} min · ${recipe.ingredients?.length||0} ingredients`:special?.note||'Choose a dinner and a cook.';return `<article class="meal-day ${key===today?'today':''}" data-day="${key}"><div class="meal-date"><strong>${formatDate(date,{weekday:'long'})}</strong><span>${formatDate(date,{month:'short',day:'numeric'})}</span></div><label>Dinner<select data-plan-choice="${key}">${choiceOptions(slot.choice)}</select></label><label>Cook<select data-plan-cook="${key}">${cookOptions(slot.cook||'Unassigned')}</select></label><div class="meal-note">${esc(note)}</div>${special?`<span class="meal-special">${esc(special.name)}</span>`:''}</article>`;}).join('');}

  function renderRecipes(){const q=(document.getElementById('recipeSearch')?.value||'').trim().toLowerCase();const list=[...state.recipes].filter(r=>!q||[r.name,r.createdBy,r.category].some(v=>String(v||'').toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('recipeShelf').innerHTML=list.length?list.map(r=>`<article class="recipe-card"><div class="recipe-card-image">${r.sourceImageUrl?`<img src="${esc(r.sourceImageUrl)}" alt="">`:'<span>🍲</span>'}</div><div class="recipe-card-copy"><p class="eyebrow">${esc(r.category||'Recipe')}</p><h3>${esc(r.name)}</h3><p>${r.createdBy?`By ${esc(r.createdBy)} · `:''}${Number(r.totalMinutes)||Number(r.prepMinutes||0)+Number(r.cookMinutes||0)||'?'} min · ${(r.ingredients||[]).length} ingredients</p><div class="recipe-card-actions"><button data-view-recipe="${esc(r.id)}">View</button><button data-edit-recipe="${esc(r.id)}">Edit</button><button data-print-recipe="${esc(r.id)}">Print</button><button data-email-recipe="${esc(r.id)}">Email</button>${r.url?`<a href="${esc(r.url)}" target="_blank" rel="noopener">Source</a>`:''}</div></div></article>`).join(''):'<div class="empty">No recipes match.</div>';}

  function openRecipeForm(recipe=null){const d=document.getElementById('recipeDialog'),f=document.getElementById('recipeForm');f.reset();f.elements.id.value=recipe?.id||'';f.elements.name.value=recipe?.name||'';f.elements.createdBy.value=recipe?.createdBy||'';f.elements.prepMinutes.value=recipe?.prepMinutes||0;f.elements.cookMinutes.value=recipe?.cookMinutes||0;f.elements.servings.value=recipe?.servings||'';f.elements.url.value=recipe?.url||'';f.elements.ingredients.value=(recipe?.ingredients||[]).join('\n');f.elements.instructions.value=(recipe?.instructions||[]).join('\n');f.elements.notes.value=recipe?.notes||'';document.getElementById('recipeDialogTitle').textContent=recipe?`Edit ${recipe.name}`:'Add family recipe';d.showModal();}
  function saveRecipeForm(form){const existing=state.recipes.find(r=>r.id===form.elements.id.value);const recipe={...(existing||{}),id:existing?.id||id(),name:form.elements.name.value.trim(),createdBy:form.elements.createdBy.value.trim(),category:existing?.category||'Dinner',prepMinutes:Number(form.elements.prepMinutes.value)||0,cookMinutes:Number(form.elements.cookMinutes.value)||0,servings:form.elements.servings.value.trim(),url:form.elements.url.value.trim(),ingredients:lines(form.elements.ingredients.value),instructions:lines(form.elements.instructions.value),notes:form.elements.notes.value.trim(),updatedAt:new Date().toISOString(),createdAt:existing?.createdAt||new Date().toISOString()};recipe.totalMinutes=recipe.prepMinutes+recipe.cookMinutes||existing?.totalMinutes||0;state.recipes=[recipe,...state.recipes.filter(r=>r.id!==recipe.id)];save();form.closest('dialog').close();renderRecipes();renderPlan();renderGrocery();toast('Recipe saved.',`${recipe.name} is ready for the meal plan.`);}
  function viewRecipe(recipe){if(!recipe)return;const box=document.getElementById('recipeView');box.className='dialog-card recipe-view';box.innerHTML=`<button type="button" class="dialog-close" data-close-view>×</button><p class="eyebrow">${esc(recipe.category||'Recipe')}</p><h2>${esc(recipe.name)}</h2><p>${recipe.createdBy?`By ${esc(recipe.createdBy)} · `:''}${recipe.servings?`Serves ${esc(recipe.servings)} · `:''}${recipe.totalMinutes||'?'} minutes</p><div class="recipe-columns"><section><h3>Ingredients</h3><ul>${(recipe.ingredients||[]).map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section><section><h3>Instructions</h3><ol>${(recipe.instructions||[]).map(v=>`<li>${esc(v)}</li>`).join('')}</ol></section></div>${recipe.notes?`<p><strong>Notes:</strong> ${esc(recipe.notes)}</p>`:''}<div class="button-row recipe-view-actions"><button class="primary" data-print-recipe="${esc(recipe.id)}">Print</button><button class="secondary" data-email-recipe="${esc(recipe.id)}">Email</button>${recipe.url?`<a class="secondary" href="${esc(recipe.url)}" target="_blank" rel="noopener">Original recipe</a>`:''}</div>`;document.getElementById('recipeViewDialog').showModal();}
  function printRecipe(recipe){if(!recipe)return;viewRecipe(recipe);setTimeout(()=>window.print(),80);}
  function emailRecipe(recipe){if(!recipe)return;const body=[recipe.name,'',...(recipe.ingredients||[]).map(v=>`• ${v}`),'','Instructions',...(recipe.instructions||[]).map((v,i)=>`${i+1}. ${v}`),recipe.url?'':null,recipe.url?`Source: ${recipe.url}`:null].filter(v=>v!==null).join('\n');location.href=`mailto:?subject=${encodeURIComponent(`Recipe: ${recipe.name}`)}&body=${encodeURIComponent(body)}`;}

  async function importRecipe(form){const input=form.elements.recipeUrl,status=document.getElementById('importStatus'),button=form.querySelector('button[type="submit"]');let url;try{url=new URL(input.value.trim());if(url.protocol!=='https:')throw new Error();}catch{toast('That URL needs another look.','Paste a full HTTPS recipe link.');return;}button.disabled=true;button.textContent='Reading recipe…';status.textContent='The raccoon is checking the recipe card…';try{const response=await fetch(`/api/recipe-context?url=${encodeURIComponent(url.href)}`,{cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Recipe import failed.');const existing=state.recipes.find(r=>r.url===data.sourceUrl||r.url===url.href);const recipe={...(existing||{}),id:existing?.id||id(),name:data.name||url.hostname,createdBy:existing?.createdBy||'',category:form.elements.category.value||'Dinner',prepMinutes:Number(data.prepMinutes)||0,cookMinutes:Number(data.cookMinutes)||0,totalMinutes:Number(data.totalMinutes)||Number(data.prepMinutes||0)+Number(data.cookMinutes||0),servings:data.servings||'',ingredients:Array.isArray(data.ingredients)?data.ingredients:[],instructions:Array.isArray(data.instructions)?data.instructions:[],sourceImageUrl:data.imageUrl||'',url:data.sourceUrl||url.href,notes:existing?.notes||'',createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};state.recipes=[recipe,...state.recipes.filter(r=>r.id!==recipe.id)];save();input.value='';renderRecipes();renderPlan();status.textContent=`Saved ${recipe.name} with ${recipe.ingredients.length} ingredients.`;toast('Recipe created from URL.',recipe.name);}catch(error){status.textContent=error.message||'The recipe site could not be read.';toast('Recipe import failed.',status.textContent);}finally{button.disabled=false;button.textContent='Create recipe from URL';}}

  function normalize(value){return String(value||'').toLowerCase().normalize('NFKD').replace(/\([^)]*\)/g,' ').replace(/\b\d+(?:[./]\d+)?\b/g,' ').replace(/\b(cups?|tablespoons?|tbsp|teaspoons?|tsp|ounces?|oz|pounds?|lbs?|grams?|kg|ml|cloves?|cans?|packages?|jars?|bottles?|containers?|bunches?|heads?|stalks?|sprigs?|slices?|pieces?|pinches?|dashes?)\b/g,' ').replace(/\b(fresh|frozen|dried|ground|minced|chopped|diced|sliced|shredded|grated|crushed|divided|softened|melted|cooked|uncooked|boneless|skinless|large|small|medium|optional|to taste|for serving|plus more)\b/g,' ').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();}
  function canonical(value){let t=normalize(String(value||'').split(',')[0]);[['scallions','green onion'],['garbanzo beans','chickpeas'],['blue cheese crumbles','blue cheese'],['chicken breasts','chicken breast'],['chicken cutlets','chicken breast'],['panko','breadcrumbs']].forEach(([a,b])=>{t=t.replace(new RegExp(`\\b${a}\\b`,'g'),b)});return t;}
  function category(name){const t=canonical(name);if(/apple|avocado|banana|berry|broccoli|cabbage|carrot|celery|cilantro|corn|cucumber|garlic|greens|herb|lemon|lime|lettuce|mango|mushroom|onion|orange|peach|pepper|potato|spinach|tomato|zucchini|parsley/.test(t))return'Produce';if(/chicken|beef|steak|pork|turkey|sausage|bacon|fish|salmon|shrimp|tuna|taco protein/.test(t))return'Meat & Seafood';if(/cheese|parmesan|milk|cream|butter|yogurt|egg/.test(t))return'Dairy & Refrigerated';if(/frozen|freezer|ice cream/.test(t))return'Frozen';if(/bread|bun|pita|tortilla|taco shell|baguette|bagel/.test(t))return'Bakery & Bread';if(/rice|pasta|noodle|flour|breadcrumbs|sugar|oil|vinegar|sauce|dressing|mustard|mayo|spice|seasoning|broth|stock|beans|nuts|seeds|bouillon|thyme|bay leaves|tomato paste|salt/.test(t))return'Pantry';return'Other';}
  function pantryMatch(itemKey){return state.pantry.find(p=>{const pk=canonical(p.name);return pk===itemKey||pk.includes(itemKey)||itemKey.includes(pk);})||null;}
  function groceryModel(){const map=new Map();weekDates().forEach(date=>{const key=dateKey(date);const choice=state.plan[`${key}:dinner`]?.choice;const recipe=recipeForChoice(choice);if(!recipe)return;(recipe.ingredients||[]).forEach(line=>{const k=canonical(line)||normalize(line)||line.toLowerCase();if(!k)return;const item=map.get(k)||{key:k,name:k.replace(/\b\w/g,c=>c.toUpperCase()),requirements:[],recipes:new Set(),category:category(k)};if(!item.requirements.includes(line))item.requirements.push(line);item.recipes.add(`${recipe.name} (${formatDate(date,{weekday:'short'})})`);map.set(k,item);});});state.groceryExtras.forEach(extra=>{const k=canonical(extra.name)||normalize(extra.name)||extra.id;if(!map.has(k))map.set(k,{key:k,name:extra.name,requirements:[extra.name],recipes:new Set(['Added manually']),category:category(extra.name),extraId:extra.id});});return [...map.values()].map(item=>{const pantry=pantryMatch(item.key);return {...item,pantry,pantryStatus:pantry?.status||'need'};});}
  function renderGrocery(){const items=groceryModel(),review=currentReview();const hidden=items.filter(i=>i.pantryStatus==='plenty'||review[i.key]).length;const low=items.filter(i=>i.pantryStatus==='low'&&!review[i.key]).length;const buy=items.length-hidden;document.getElementById('grocerySummary').innerHTML=`<span class="summary-chip">${items.length} ingredients</span><span class="summary-chip">${buy} to buy/check</span><span class="summary-chip">${low} low in pantry</span><span class="summary-chip">${hidden} already covered</span>`;const visible=items.filter(i=>i.pantryStatus!=='plenty');const groups=CATEGORIES.map(cat=>({cat,items:visible.filter(i=>i.category===cat)})).filter(g=>g.items.length);document.getElementById('groceryList').innerHTML=groups.length?groups.map(g=>`<section class="grocery-group"><h3>${g.cat}</h3>${g.items.map(item=>{const checked=Boolean(review[item.key]);return `<label class="grocery-item ${checked?'checked':''}" data-grocery-row="${esc(item.key)}"><input type="checkbox" data-grocery-check="${esc(item.key)}" ${checked?'checked':''}><span><strong>${esc(item.name)}</strong><small>${esc(item.requirements.join(' + '))}${item.pantryStatus==='low'?` · Pantry says ${esc(item.pantry?.name||item.name)} is low`:''}</small></span><span class="grocery-source">${esc([...item.recipes].join(' · '))}</span></label>`;}).join('')}</section>`).join(''):'<div class="empty">The meal plan is covered. Either you are stocked or the raccoon is suspiciously efficient.</div>';}
  function updateGroceryCheck(box){const review=currentReview(),key=box.dataset.groceryCheck;if(box.checked)review[key]=true;else delete review[key];save();box.closest('.grocery-item')?.classList.toggle('checked',box.checked);const items=groceryModel();const hidden=items.filter(i=>i.pantryStatus==='plenty'||review[i.key]).length;const low=items.filter(i=>i.pantryStatus==='low'&&!review[i.key]).length;const buy=items.length-hidden;document.getElementById('grocerySummary').innerHTML=`<span class="summary-chip">${items.length} ingredients</span><span class="summary-chip">${buy} to buy/check</span><span class="summary-chip">${low} low in pantry</span><span class="summary-chip">${hidden} already covered</span>`;}
  function copyGrocery(){const review=currentReview();const need=groceryModel().filter(i=>i.pantryStatus!=='plenty'&&!review[i.key]);const text=CATEGORIES.flatMap(cat=>{const items=need.filter(i=>i.category===cat);return items.length?[cat.toUpperCase(),...items.map(i=>`☐ ${i.requirements.join(' + ')}${i.pantryStatus==='low'?' (low in pantry)':''}`),'']:[];}).join('\n').trim()||'Nothing left to buy.';navigator.clipboard.writeText(text).then(()=>toast('Shopping list copied.','Ready to paste into your grocery app.')).catch(()=>toast('Copy did not work.','The list is still visible on screen.'));}

  function renderPantry(){state.pantry=Array.isArray(state.pantry)?state.pantry:[];document.getElementById('pantryList').innerHTML=state.pantry.length?[...state.pantry].sort((a,b)=>a.name.localeCompare(b.name)).map(p=>`<article class="pantry-item"><div><strong>${esc(p.name)}</strong><small>${esc(p.quantity||'Quantity not set')}</small></div><span class="status ${esc(p.status)}">${esc(p.status)}</span><div class="pantry-actions"><button data-pantry-status="${esc(p.id)}" data-status="plenty">Plenty</button><button data-pantry-status="${esc(p.id)}" data-status="low">Low</button><button data-pantry-status="${esc(p.id)}" data-status="out">Out</button><button data-remove-pantry="${esc(p.id)}">Remove</button></div></article>`).join(''):'<div class="empty">The pantry is empty. Add only the things worth tracking.</div>';}

  function changePlan(select,type){const date=type==='choice'?select.dataset.planChoice:select.dataset.planCook;const key=`${date}:dinner`;state.plan[key] ||= {choice:'',cook:'Unassigned'};if(type==='choice')state.plan[key].choice=select.value;else state.plan[key].cook=select.value;save();const card=select.closest('.meal-day');const slot=state.plan[key];const recipe=recipeForChoice(slot.choice),special=specialForChoice(slot.choice);const note=recipe?`${recipe.totalMinutes||'?'} min · ${recipe.ingredients?.length||0} ingredients`:special?.note||'Choose a dinner and a cook.';card.querySelector('.meal-note').textContent=note;const old=card.querySelector('.meal-special');if(old)old.remove();if(special){const s=document.createElement('span');s.className='meal-special';s.textContent=special.name;card.appendChild(s);}renderGrocery();}

  function start(){ensureSeeds();state.pantry=Array.isArray(state.pantry)?state.pantry:[];state.groceryExtras=Array.isArray(state.groceryExtras)?state.groceryExtras:[];state.groceryReview=state.groceryReview&&typeof state.groceryReview==='object'?state.groceryReview:{};renderPlan();renderRecipes();renderPantry();renderGrocery();route((location.hash||'#plan').slice(1));
    document.addEventListener('click',event=>{const nav=event.target.closest('[data-route]');if(nav)return route(nav.dataset.route);if(event.target.closest('#quickRecipeButton,#manualRecipeButton'))return openRecipeForm();if(event.target.closest('[data-close-dialog]'))return document.getElementById('recipeDialog').close();if(event.target.closest('[data-close-view]'))return document.getElementById('recipeViewDialog').close();const v=event.target.closest('[data-view-recipe]');if(v)return viewRecipe(state.recipes.find(r=>r.id===v.dataset.viewRecipe));const e=event.target.closest('[data-edit-recipe]');if(e)return openRecipeForm(state.recipes.find(r=>r.id===e.dataset.editRecipe));const p=event.target.closest('[data-print-recipe]');if(p)return printRecipe(state.recipes.find(r=>r.id===p.dataset.printRecipe));const m=event.target.closest('[data-email-recipe]');if(m)return emailRecipe(state.recipes.find(r=>r.id===m.dataset.emailRecipe));if(event.target.closest('#copyGrocery'))return copyGrocery();if(event.target.closest('#resetGrocery')){state.groceryReview[weekKey()]={};save();renderGrocery();return toast('Grocery review reset.');}const ps=event.target.closest('[data-pantry-status]');if(ps){const item=state.pantry.find(x=>x.id===ps.dataset.pantryStatus);if(item){item.status=ps.dataset.status;save();renderPantry();renderGrocery();}return;}const pr=event.target.closest('[data-remove-pantry]');if(pr){state.pantry=state.pantry.filter(x=>x.id!==pr.dataset.removePantry);save();renderPantry();renderGrocery();return;}});
    document.addEventListener('change',event=>{if(event.target.matches('[data-plan-choice]'))return changePlan(event.target,'choice');if(event.target.matches('[data-plan-cook]'))return changePlan(event.target,'cook');if(event.target.matches('[data-grocery-check]'))return updateGroceryCheck(event.target);});
    document.getElementById('recipeForm').addEventListener('submit',e=>{e.preventDefault();saveRecipeForm(e.currentTarget);});document.getElementById('recipeImportForm').addEventListener('submit',e=>{e.preventDefault();importRecipe(e.currentTarget);});document.getElementById('recipeSearch').addEventListener('input',renderRecipes);document.getElementById('pantryForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;state.pantry.push({id:id(),name:f.elements.name.value.trim(),quantity:f.elements.quantity.value.trim(),status:f.elements.status.value});save();f.reset();renderPantry();renderGrocery();toast('Pantry updated.');});document.getElementById('groceryExtraForm').addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;state.groceryExtras.push({id:id(),name:f.elements.name.value.trim()});save();f.reset();renderGrocery();});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
